title: Ruitao Xue
description: Academic personal website of Ruitao Xue.
remote_theme: pages-themes/cayman@v0.2.0
url: https://firepond.github.io
baseurl: ""
author: Ruitao Xue
github_username: firepond
header_pages:
  - index.md
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme